version: '4'

services:
  database_initializer:
    image: python:3.12-slim
    volumes:
      - persistent-storage:/persistent  # Shared database volume
      - ./database_setup.py:/app/database_setup.py
    working_dir: /app
    command: ["python", "database_setup.py"]
    networks:
      - mynetwork
    deploy:
      restart_policy:
        condition: none

  vulnerable-site:
    build: ./vulnerable-site
    ports:
      - "5000:5000"
    environment:
      - DASHBOARD_URL=http://dashboard:5001/report-attack
    depends_on:
      - dashboard
      - database_initializer
    networks:
      - mynetwork
    volumes:
      - persistent-storage:/persistent  # Shared database volume
      - shared-storage:/shared          # Shared volume for other files like PCAP files

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - database_initializer
    networks:
      - mynetwork
    volumes:
      - persistent-storage:/persistent  # Shared database volume

  status-checker:
    build: ./status_checker
    depends_on:
      - database_initializer
    networks:
      - mynetwork
    volumes:
      - persistent-storage:/persistent  # Shared database volume
      - ./status_checker/pcap_files:/app/pcap_files  # Mount local pcap_files to /app/pcap_files inside the container
      - shared-storage:/shared  # Mount shared volume to allow access to PCAP files

networks:
  mynetwork:
    driver: bridge

volumes:
  persistent-storage:
    driver: local
  shared-storage:
    driver: local